name: pool_and_chill
description: "A new Flutter project."

# Evita la publicación accidental en pub.dev
publish_to: 'none' 

# Versión de la aplicación
version: 1.0.0+1

# Requerimiento de SDK
environment:
  sdk: ^3.6.0

# Dependencias principales
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

# Dependencias para desarrollo y testing
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/


